#
# GL3W_FOUND
# GL3W_INCLUDE_DIR
# GL3W_LIBRARIES

if(NOT GL3W_FOUND)

FIND_PATH(GL3W_INCLUDE_DIR GL/GL3W.h
  PATHS
    NO_DEFAULT_PATH
    )

FIND_LIBRARY( GL3W_LIBRARIES NAMES GL3W
  PATHS
    NO_DEFAULT_PATH
)

SET(GL3W_FOUND "NO")
IF (GL3W_INCLUDE_DIR AND GL3W_LIBRARIES)
	SET(GL3W_FOUND "YES")
ENDIF (GL3W_INCLUDE_DIR AND GL3W_LIBRARIES)

if(GL3W_FOUND)
  message(STATUS "Found GL3W: ${GL3W_INCLUDE_DIR}")
else(GL3W_FOUND)
  if (NOT GL3W_FIND_QUIETLY)
    message(FATAL_ERROR "could NOT find GL3W")
  endif (NOT GL3W_FIND_QUIETLY)
endif(GL3W_FOUND)

endif(NOT GL3W_FOUND)


